DROP TABLE IF EXISTS project_worker;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS worker;
DROP TABLE IF EXISTS client;

CREATE TABLE worker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(1000) NOT NULL CHECK (LENGTH(name) >= 2),
    birthday DATE NOT NULL CHECK (birthday > DATE '1900-01-01'),
    level VARCHAR(10) NOT NULL CHECK (level IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    salary INT NOT NULL CHECK (salary >= 100 AND salary <= 100000)
);

CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(1000) NOT NULL CHECK (LENGTH(name) >= 2)
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    name VARCHAR(1000) NOT NULL,
    start_date DATE NOT NULL,
    finish_date DATE NOT NULL,
    CONSTRAINT fk_project_client FOREIGN KEY (client_id) REFERENCES client(id),
    CONSTRAINT chk_project_dates CHECK (finish_date > start_date)
);

CREATE TABLE project_worker (
    project_id BIGINT NOT NULL,
    worker_id BIGINT NOT NULL,
    PRIMARY KEY (project_id, worker_id),
    CONSTRAINT fk_project_worker_project FOREIGN KEY (project_id) REFERENCES project(id),
    CONSTRAINT fk_project_worker_worker FOREIGN KEY (worker_id) REFERENCES worker(id)
);
